/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreCartRouteImport } from './routes/_store/cart'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreShopRouteImport } from './routes/_store/shop'
import { Route as StoreOrderIdRouteImport } from './routes/_store/order.$id'
import { Route as StoreProductIdRouteImport } from './routes/_store/product.$id'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderIdRoute = StoreOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/shop': typeof StoreShopRoute
  '/order/$id': typeof StoreOrderIdRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesByTo {
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/shop': typeof StoreShopRoute
  '/': typeof StoreIndexRoute
  '/order/$id': typeof StoreOrderIdRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/': typeof StoreIndexRoute
  '/_store/order/$id': typeof StoreOrderIdRoute
  '/_store/product/$id': typeof StoreProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cart' | '/checkout' | '/shop' | '/order/$id' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/cart' | '/checkout' | '/shop' | '/' | '/order/$id' | '/product/$id'
  id:
    | '__root__'
    | '/_store'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/shop'
    | '/_store/'
    | '/_store/order/$id'
    | '/_store/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/order/$id': {
      id: '/_store/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof StoreOrderIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/product/$id': {
      id: '/_store/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrderIdRoute: typeof StoreOrderIdRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreShopRoute: StoreShopRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrderIdRoute: StoreOrderIdRoute,
  StoreProductIdRoute: StoreProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
