// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulfomwxlvucggvunwedn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZm9td3hsdnVjZ2d2dW53ZWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA2OTM0NjMsImV4cCI6MjEwNjI2OTQ2M30.q1X0NJj9CsY-fOJ7xT-vmhmHCQscyuCPguzN164T848";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});